name: Build Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. v1.18.7-beta1)'
        required: true

      branch:
        description: 'Branch to release from (e.g. main)'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build release
        env:
          REPO_URL: ${{ vars.REPO_URL }}
          UPLOAD: "no"
        run: |
          ./make-release ${{ github.event.inputs.branch }} ${{ github.event.inputs.version }}
