name: Build Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. v1.18.7-beta1)'
        required: true

      branch:
        description: 'Branch to release from (e.g. main)'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build release
        env:
          REPO_URL: ${{ vars.REPO_URL }}
          UPLOAD: "no"
        run: |
          ./make-release ${{ github.event.inputs.branch }} ${{ github.event.inputs.version }}

      - uses: actions/upload-artifact@v4
        with:
          name: boriel-basic-win-x32
          path: dist/zxbasic-${{ github.event.inputs.version }}-win32.zip
          retention-days: 90

      - uses: actions/upload-artifact@v4
        with:
          name: boriel-basic-linux-x64
          path: dist/zxbasic-${{ github.event.inputs.version }}-linux64.tar.gz
          retention-days: 90

      - uses: actions/upload-artifact@v4
        with:
          name: boriel-basic-macos
          path: dist/zxbasic-${{ github.event.inputs.version }}-macos.tar.gz
          retention-days: 90
